DROP DATABASE IF EXISTS RESTAURANTDB;

CREATE DATABASE RESTAURANTDB
  CHARSET = 'utf8'
  COLLATE = 'utf8_general_ci';

CREATE TABLE RESTAURANTDB.USERS
(
  ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME    VARCHAR(128)    NOT NULL UNIQUE,
  PASSWORD    VARCHAR(128)    NOT NULL,
  PHONE_NO    VARCHAR(13)     NOT NULL,
  ROLE		  VARCHAR(10)     NOT NULL
);

CREATE TABLE RESTAURANTDB.ADDRESSES
(
  ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CITY           VARCHAR (64)    NOT NULL,
  STREET_ADDRESS VARCHAR (128)   NOT NULL,
  USER_ID    BIGINT UNSIGNED NOT NULL,
  CONSTRAINT ADDRESSES_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES RESTAURANTDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE RESTAURANTDB.COMPLAINS
(
  ID         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COMPLAIN  TEXT,   
  USER_ID    BIGINT UNSIGNED NOT NULL,
  CONSTRAINT COMPLAINS_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES RESTAURANTDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE RESTAURANTDB.ITEMS
(
  ID          BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(128)     NOT NULL,
  DESCRIPTION VARCHAR(128)     NOT NULL,
  PRICE       FLOAT UNSIGNED NOT NULL,
  IMG_URL     VARCHAR(100)
);

CREATE TABLE RESTAURANTDB.ORDERS
(
  ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TOTAL_PRICE    FLOAT UNSIGNED NOT NULL,
  USER_ID    BIGINT UNSIGNED NOT NULL,
  CONSTRAINT ORDERS_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES RESTAURANTDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE RESTAURANTDB.ORDER_ITEMS
(
  ORDER_ID BIGINT UNSIGNED NOT NULL,
  ITEM_ID  BIGINT UNSIGNED NOT NULL,
  QUANTITY INTEGER UNSIGNED NOT NULL,
  CONSTRAINT ORDER_ITEMS_ORDERS_FK
  FOREIGN KEY (ORDER_ID) REFERENCES RESTAURANTDB.ORDERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT ORDER_ITEMS_ITEMS_FK
  FOREIGN KEY (ITEM_ID) REFERENCES RESTAURANTDB.ITEMS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);


use RESTAURANTDB;

INSERT INTO USERS(USERNAME, PASSWORD, PHONE_NO, ROLE) VALUES
("Zaher", "PASS", "01000000000", "user"),
("Salah", "2", "01000000001", "user"),
("Mo'men", "3", "01000000002", "user"),
("Fawzi", "4", "01000000003", "user"),
("Mitchoz", "5", "01000000004", "user");


INSERT INTO ADDRESSES(CITY, STREET_ADDRESS, USER_ID) VALUES
("Cairo", "1st", 1),
("Alex", "10th", 1),
("NY", "3rd", 1),
("Cairo", "2nd", 2),
("Cairo", "3rd", 3),
("Cairo", "4th", 4),
("Cairo", "5th", 5);


INSERT INTO ITEMS(NAME, DESCRIPTION, PRICE, IMG_URL) VALUES
("BBQ PIZZA","PIZZA With BBQ" ,10, "img/pizza.jpg"),
("PIZZA MONSTER","PIZZA With all types of chicken, cheese and mushhrom" ,10, "img/pizza.jpg"),
("MIXED CHEESE", "PIZZA with all types of cheese",20, "img/pizza.jpg");

INSERT INTO ORDERS(TOTAL_PRICE, USER_ID) VALUES
(100, 1),
(200, 2);

INSERT INTO ORDER_ITEMS(ORDER_ID, ITEM_ID, QUANTITY) VALUES
(1, 1, 2),
(1, 2, 3),
(2, 1, 4);